### ISSUE TITLE
Versatility Improvements / Fixes

### ISSUE THREAD

**Issue by ghost** [markski1/SAMP-3dspeed#5]
I think for the include to be more versatile the following could be supported:

- Support custom offsets for the 3d texts (these can be per-vehicle or per-player potentially); [this code](https://github.com/markski1/SAMP-3dspeed/blob/master/3dspeed.inc#L314-L320) could just be made to adjust for that. One thing is that these dimensions should be capped at a certain number so that people aren't putting their car's speedo 1000m away from them. Iterators over a fixed array is a solution I'd go for; but there's many possibilities depending on what is to be supported. (Customization like this could be paired up with the colors/sizes you mentioned).

For fixes/miscellaneous improvements:

- Add sampctl package definition (for easier testing/sharing).
- Correct offsets for wider vehicles.

I'm doing a PR for both of these and should submit it relatively soon, but please ping me in case I forget to.

**Comment by markski1** [comment]
I continue to fail seeing the point of sampctl's existance, but if you do it I don't have any reason to reject it, so sure.

The rest of the changes are very welcome, thanks for your interest.

**Comment by ghost** [comment]
sampctl is most useful as an abstraction for `pawncc` (managing dependencies, different configurations, etc), and running a "server". For this specific case, it'd be most useful in managing dependencies (things that the library depends on to work) and dev dependencies (things that you only need to build yourself, but not after). I can quickly get library X or plugin Y without having to manage any of the `server.cfg` stuff through an uniform interface (`pawn.json`). It offers other abstractions that are personally not as useful for me, though I may be forgetting some.

In reality, you could very well use your own style of abstraction (say a bunch of Python scripts, I'm doing that for a gamemode project) that will let you tailor what you want exactly how you want it and what the priorities are. Despite some disagreements I have with the tool and how it's developed, it's played a very large role in introducing the need and use of similar abstractions to the SA-MP (and beyond) community.

You can follow the process of my updates [at my fork](https://github.com/lagoevia/SAMP-3dspeed). Progress will be somewhat sporadic as I'm somewhat busy with school/work/etc, but it's an interesting project and I've seen other areas that it can improve upon (some of those code improvements are already active in the fork). I'll make a PR when it's done, but feel free to look at it and reference/ask anytime.

**Comment by markski1** [comment]
@lagoevia any updates? If you don't wish or have time to finish what you were making you could just push whatever you have done

**Comment by ghost** [comment]
> 
> 
> @lagoevia any updates? If you don't wish or have time to finish what you were making you could just push whatever you have done

I'm continuing some of the work on this right now. I mentioned progress may be sporadic, but I may get a large bulk of what I'm getting in now. Will make a PR when it's ready/in a partially ready state, and update here.

**Update**: Majority of the fixes are in. Last thing left to do is the per-vehicle offset list and the ability for per-player offsets. Once that's done, PR will be up with some comments with explanations/etc.

**Comment by markski1** [comment]
Safe to say this will not happen
